# Basic Pytorch 

Creating Tensors

In [8]:
# helper function that helps us to describe various properties of tensors.
def describe(x):
    print("Type : {}".format(x.type()))
    print("Shape/size : {}".format(x.shape))
    print("Values : \n{}\n".format(x))

In [9]:
# Creating tensor with torch.Tensor
import torch
describe(torch.Tensor(2,3))

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[-1.9619e-32,  3.0761e-41, -2.0823e-32],
        [ 3.0761e-41,  1.1210e-43,  0.0000e+00]])



In [10]:
describe(torch.rand(2,3)) # Uniform random
describe(torch.randn(2,3)) # random normal

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[4.6971e-01, 9.7573e-01, 5.1737e-05],
        [6.6069e-01, 9.2494e-01, 1.8244e-01]])

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[ 1.5903, -0.7021,  1.0048],
        [ 0.4791, -1.1222, -0.1503]])



In [12]:
# creating tensor, filled with same scaler
describe(torch.zeros(2,3))
x = torch.ones(2,3)
describe(x)
x.fill_(5) # filling with 5 using fill_ function, inplace operations
describe(x)

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[5., 5., 5.],
        [5., 5., 5.]])



In [14]:
# creating tensor using python list
describe(torch.Tensor([[1,2,3],
                        [4,5,6]]))

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [15]:
# numpy array to tensor
import numpy as np
npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

Type : torch.DoubleTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[0.0987, 0.5766, 0.6846],
        [0.3974, 0.1256, 0.6732]], dtype=torch.float64)



In [16]:
x = torch.FloatTensor([[1,2,3],
                        [4,5,6]])
describe(x)

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



In [18]:
x = x.long()
describe(x)

Type : torch.LongTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[1, 2, 3],
        [4, 5, 6]])



In [19]:
x = torch.tensor([[1,2,3],
                    [4,5,6]],dtype = torch.int64)
describe(x)

Type : torch.LongTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[1, 2, 3],
        [4, 5, 6]])



In [20]:
x =x.float()
describe(x)

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[1., 2., 3.],
        [4., 5., 6.]])



Tensor Operations

In [21]:
x = torch.randn(2,3)
describe(x)

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[ 0.1956, -1.2471, -0.6217],
        [ 1.6830, -0.2809,  0.6461]])



In [22]:
describe(torch.add(x,x))

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[ 0.3913, -2.4941, -1.2433],
        [ 3.3660, -0.5618,  1.2923]])



In [23]:
describe(x+x)

Type : torch.FloatTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[ 0.3913, -2.4941, -1.2433],
        [ 3.3660, -0.5618,  1.2923]])



In [24]:
x = torch.arange(6)
describe(x)

Type : torch.LongTensor
Shape/size : torch.Size([6])
Values : 
tensor([0, 1, 2, 3, 4, 5])



In [25]:
x = x.view(2,3)
describe(x)

Type : torch.LongTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [26]:
describe(torch.sum(x,dim= 0))

Type : torch.LongTensor
Shape/size : torch.Size([3])
Values : 
tensor([3, 5, 7])



In [27]:
describe(torch.sum(x,dim= 1))


Type : torch.LongTensor
Shape/size : torch.Size([2])
Values : 
tensor([ 3, 12])



In [28]:
describe(torch.transpose(x,0,1))

Type : torch.LongTensor
Shape/size : torch.Size([3, 2])
Values : 
tensor([[0, 3],
        [1, 4],
        [2, 5]])



Indexing, Slicing and Joining

In [29]:
x  = torch.arange(6).view(2,3)
describe(x)

Type : torch.LongTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [30]:
describe(x[:1,:2])

Type : torch.LongTensor
Shape/size : torch.Size([1, 2])
Values : 
tensor([[0, 1]])



In [36]:
indices = torch.LongTensor([0,2])
describe(torch.index_select(x,dim = 1,index = indices))

Type : torch.LongTensor
Shape/size : torch.Size([2, 2])
Values : 
tensor([[0, 2],
        [3, 5]])



In [38]:
indices = torch.LongTensor([0,0])
describe(torch.index_select(x,dim = 0,index = indices))

Type : torch.LongTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[0, 1, 2],
        [0, 1, 2]])



In [40]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,1])
describe(x[row_indices,col_indices])

Type : torch.LongTensor
Shape/size : torch.Size([2])
Values : 
tensor([0, 4])



In [41]:
row_indices,col_indices

(tensor([0, 1]), tensor([0, 1]))

In [42]:
# dimention based tensor operations
x = torch.arange(6)
describe(x)

Type : torch.LongTensor
Shape/size : torch.Size([6])
Values : 
tensor([0, 1, 2, 3, 4, 5])



In [43]:
x = x.view(2,3)
describe(x)

Type : torch.LongTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [44]:
describe(torch.sum(x,dim = 0))

Type : torch.LongTensor
Shape/size : torch.Size([3])
Values : 
tensor([3, 5, 7])



In [45]:
describe(torch.sum(x,dim = 1))

Type : torch.LongTensor
Shape/size : torch.Size([2])
Values : 
tensor([ 3, 12])



In [46]:
describe(torch.transpose(x,0,1))

Type : torch.LongTensor
Shape/size : torch.Size([3, 2])
Values : 
tensor([[0, 3],
        [1, 4],
        [2, 5]])



In [47]:
x = torch.arange(6).view(2,3)
describe(x)

Type : torch.LongTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [48]:
describe(torch.cat([x,x],dim = 0))

Type : torch.LongTensor
Shape/size : torch.Size([4, 3])
Values : 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])



In [49]:
describe(torch.cat([x,x],dim = 1))

Type : torch.LongTensor
Shape/size : torch.Size([2, 6])
Values : 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])



In [50]:
describe(torch.stack([x,x]))

Type : torch.LongTensor
Shape/size : torch.Size([2, 2, 3])
Values : 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])



In [52]:
# Linear algebra on tensors
x1 = torch.arange(6).view(2,3)
describe(x1)

Type : torch.LongTensor
Shape/size : torch.Size([2, 3])
Values : 
tensor([[0, 1, 2],
        [3, 4, 5]])



In [56]:
x2 = torch.ones(3,2)
x2[:,1] += 1
describe(x2)

Type : torch.FloatTensor
Shape/size : torch.Size([3, 2])
Values : 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])



In [59]:
describe(torch.mm(x1.float(),x2))

Type : torch.FloatTensor
Shape/size : torch.Size([2, 2])
Values : 
tensor([[ 3.,  6.],
        [12., 24.]])



In [61]:
# Tensors and computational graphs
x = torch.ones(2,2,requires_grad=True)
describe(x)
print(x.grad is None)

Type : torch.FloatTensor
Shape/size : torch.Size([2, 2])
Values : 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

True


In [62]:
y = (x+2) * (x+5) + 3
describe(y)
print(x.grad is None)

Type : torch.FloatTensor
Shape/size : torch.Size([2, 2])
Values : 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)

True


In [63]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type : torch.FloatTensor
Shape/size : torch.Size([])
Values : 
21.0

False


In [64]:
# cuda tebsors
print(torch.cuda.is_available())

False


In [67]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [68]:
x = torch.rand(3,3).to(device)
describe(x)

Type : torch.FloatTensor
Shape/size : torch.Size([3, 3])
Values : 
tensor([[0.7995, 0.2596, 0.1187],
        [0.1659, 0.1538, 0.2920],
        [0.7364, 0.2568, 0.8920]])



In [70]:
y = torch.rand(3,3)

In [71]:
cpu_device = torch.device("cpu")
y = y.to(cpu_device)
x = x.to(cpu_device)
x + y

tensor([[0.8785, 0.9204, 0.7497],
        [1.0933, 0.7871, 0.6031],
        [1.2339, 0.2969, 1.0061]])